- hosts: web_nodes
  become: true
  gather_facts: false
  
  tasks:
          - name: Installing HTTPD Software 
            package:
                    name: httpd
                    state: present

          - name: Installing PHP 
            package:
                    name: php
                    state: present

          - name: Copy the PHP webpage
            template:
                    dest: /var/www/html/index.php
                    src: index.php

            notify: web services

          - name: start httpd web server
            service:
                    name: httpd
                    state: started



- hosts: web_lbs
  become: true
  gather_facts: false

  tasks:
          - name: Installing HAProxy Software
            package:
                    name: haproxy
                    state: present

          - name: Configuring the conf file of haproxy
            template:
                    src: haproxy.cfg
                    dest: /etc/haproxy/haproxy.cfg

          - name: start the haproxy service
            service:
                      name: haproxy
                      state: started
